-- =============================================================================
-- FULL DATABASE SETUP SCRIPT
-- Generated by Database Architect Agent
-- Based on types/database.ts reconstruction + migrations
-- =============================================================================

-- Enable extension for UUIDs (if not already enabled, though gen_random_uuid is standard now)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- 1. BASE TABLES
-- ============================================

-- Table: clients
CREATE TABLE IF NOT EXISTS public.clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: users (Extends auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT, -- Ex: "Marketing Director"
    access_level TEXT CHECK (access_level IN ('MANAGER', 'CLIENT')),
    avatar_url TEXT,
    bio TEXT,
    cover_url TEXT,
    skills TEXT[],
    location TEXT,
    website TEXT,
    client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
    is_onboarded BOOLEAN DEFAULT false,
    whatsapp TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: projects
CREATE TABLE IF NOT EXISTS public.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    status TEXT CHECK (status IN ('In Progress', 'Revision', 'Completed')) DEFAULT 'In Progress',
    due_date TIMESTAMPTZ,
    progress INTEGER DEFAULT 0,
    priority BOOLEAN DEFAULT false,
    invite_code TEXT UNIQUE, -- Added from migration directly here
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: creative_goals
CREATE TABLE IF NOT EXISTS public.creative_goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT false,
    status TEXT CHECK (status IN ('Pendente', 'Em Andamento', 'Em Revisão', 'Concluído')) DEFAULT 'Pendente',
    type TEXT CHECK (type IN ('video', 'design', 'campaign')),
    due_date TIMESTAMPTZ,
    responsible_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    internal_checklist JSONB DEFAULT '[]'::jsonb, -- Added from migration directly here
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: documents
CREATE TABLE IF NOT EXISTS public.documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    goal_id UUID REFERENCES public.creative_goals(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('pdf', 'figma', 'image', 'video')),
    url TEXT NOT NULL,
    size TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: conversations
CREATE TABLE IF NOT EXISTS public.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('group', 'private')),
    avatar TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: messages
CREATE TABLE IF NOT EXISTS public.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: project_activities
CREATE TABLE IF NOT EXISTS public.project_activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    user_avatar TEXT,
    type TEXT CHECK (type IN ('comment', 'system')),
    content TEXT NOT NULL,
    system_icon TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Table: user_activities
CREATE TABLE IF NOT EXISTS public.user_activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    target TEXT,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: invitations
CREATE TABLE IF NOT EXISTS public.invitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token TEXT NOT NULL UNIQUE,
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    invited_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- ============================================
-- 2. ENABLE ROW LEVEL SECURITY
-- ============================================

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creative_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;

-- BASIC POLICY: Allow all operations for authenticated users (for now, to unblock)
-- You may want to restrict this later based on client_id
CREATE POLICY "Allow all for authenticated" ON public.clients FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.users FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.projects FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.creative_goals FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.documents FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.conversations FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.messages FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.project_activities FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.user_activities FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON public.invitations FOR ALL USING (auth.role() = 'authenticated');

-- ============================================
-- 3. MIGRATIONS INTEGRATION
-- ============================================

-- Index for projects invite code
CREATE INDEX IF NOT EXISTS idx_projects_invite_code ON public.projects(invite_code);

-- RPC for Invite Code
CREATE OR REPLACE FUNCTION get_project_by_invite_code(code text)
RETURNS TABLE (
  project_id uuid,
  project_title text,
  client_id uuid,
  client_name text,
  client_logo text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id as project_id,
    p.title as project_title,
    c.id as client_id,
    c.name as client_name,
    c.logo_url as client_logo
  FROM public.projects p
  JOIN public.clients c ON c.id = p.client_id
  WHERE p.invite_code = code;
END;
$$;

GRANT EXECUTE ON FUNCTION get_project_by_invite_code(text) TO anon, authenticated, service_role;

-- Notifications System (Condensed from 20260125_notifications.sql)
-- Note: Assuming full content was read previously, re-adding key parts here for completeness

CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link_type TEXT,
  link_id UUID,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  in_app_enabled BOOLEAN DEFAULT true,
  notify_deadlines BOOLEAN DEFAULT true,
  notify_mentions BOOLEAN DEFAULT true,
  notify_project_updates BOOLEAN DEFAULT true,
  notify_goal_completed BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can view their own preferences" ON public.notification_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own preferences" ON public.notification_preferences FOR ALL USING (auth.uid() = user_id);

-- Check output
DO $$
BEGIN
  RAISE NOTICE 'Database setup completed successfully.';
END $$;
